image:
  file: .gitpod.Dockerfile

ports:
- port: 80
  onOpen: open-preview

tasks:
  - init: sudo ./bbb-install.sh -s -- -w -a -v bionic-23 -s $GITPOD_WORKSPACE_URL -e admin@example.com
    command: bbb-conf --check
